### PR TITLE
Notice section almost done except notice_visibility

### PR DESCRIPTION
**Pull request by Arijit02**
Notice section has been done except the visibility part, if you check you will get an idea.

### CODE REVIEW

**Comment by ayan-biswas0412** [comment]
Screenshot from 2020-04-16 23-21-27
Nice Work I havent checked the backend but there is several change needed in frontend .

When requires authentication selected {
show two checkbox : 1. Faculty 2. Student

if(faculty checkbox checked )
{
give dropdown to select options : ALL FACULTY + echo faculty names in other options
} 

if(student checkbox checked )
{
give dropdown to select options : ALL STUDENTS+ echo course_codes in other options.

fetch course_codes from batch_info TABLE where status = "1";
} 

]

import this file in phpmyadmin for the newest sql .

[batch_info.zip](https://github.com/ayan-biswas0412/Juetcecoursemanagementsystem/files/4488939/batch_info.zip)

**Comment by ayan-biswas0412** [comment]
After you done just commit and push your new code here no need to do separate pull request

**Comment by ayan-biswas0412** [comment]
https://www.jeasyui.com/demo/main/index.php?plugin=ComboTreeGrid&theme=material-teal&dir=ltr&pitem=&sort=asc

you can use it for frontend purpose load the scripts in head before use .
The elements are already in 'ayan/develop2' branch in the folder jquery_ui

here is it : just git pull origin 'ayan/develop2'
[jquery_ui.zip](https://github.com/ayan-biswas0412/Juetcecoursemanagementsystem/files/4489220/jquery_ui.zip)

**Comment by ayan-biswas0412** [comment]
Also JU logo is not coming please fix that

**Review by ayan-biswas0412 — CHANGES_REQUESTED** [review]
Screenshot from 2020-04-17 03-53-43
Nice Work I havent checked the backend but there is several change needed in frontend .

When requires authentication selected {
show two checkbox : 1. Faculty 2. Student

if(faculty checkbox checked )
{
give dropdown to select options : ALL FACULTY + echo faculty names in other options
}

if(student checkbox checked )
{
give dropdown to select options : ALL STUDENTS+ echo course_codes in other options.

fetch course_codes from batch_info TABLE where status = "1";
}

]

import this file in phpmyadmin for the newest sql .

[batch_info.zip](https://github.com/ayan-biswas0412/Juetcecoursemanagementsystem/files/4489980/batch_info.zip)

**Comment by Arijit02** [comment]
Ok I am completing

**Pull request closed without merging**
